/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author olia
 */
public class manageDataUI extends javax.swing.JFrame {

    /**
     * Creates new form ArxikoMenu
     */
    public manageDataUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        insertCountryBtn = new javax.swing.JButton();
        insertDataBtn = new javax.swing.JButton();
        deleteCountryBtn = new javax.swing.JButton();
        deleteDataBtn = new javax.swing.JButton();
        chooseCountry1ComboBox = new javax.swing.JComboBox<>();
        chooseCountry2ComboBox = new javax.swing.JComboBox<>();
        chooseCountry3ComboBox = new javax.swing.JComboBox<>();
        astheneisCheckBox1 = new javax.swing.JCheckBox();
        krousmataCheckBox2 = new javax.swing.JCheckBox();
        thanatoiCheckBox3 = new javax.swing.JCheckBox();
        label1 = new java.awt.Label();
        showCountryMenuBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        menu1.setLabel("File");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Επιλογή δεδομένων Covid-19 ανά χώρα");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        insertCountryBtn.setBackground(new java.awt.Color(0, 204, 204));
        insertCountryBtn.setText("Εισαγωγή χωρών");
        insertCountryBtn.setMaximumSize(new java.awt.Dimension(135, 23));
        insertCountryBtn.setMinimumSize(new java.awt.Dimension(135, 23));
        insertCountryBtn.setPreferredSize(new java.awt.Dimension(135, 23));
        insertCountryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCountryBtnActionPerformed(evt);
            }
        });

        insertDataBtn.setBackground(new java.awt.Color(0, 204, 204));
        insertDataBtn.setText("Εισαγωγή δεδομένων");
        insertDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDataBtnActionPerformed(evt);
            }
        });

        deleteCountryBtn.setBackground(new java.awt.Color(0, 204, 204));
        deleteCountryBtn.setText("Διαγραφή χωρών");
        deleteCountryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCountryBtnActionPerformed(evt);
            }
        });

        deleteDataBtn.setBackground(new java.awt.Color(0, 204, 204));
        deleteDataBtn.setText("Διαγραφή δεδομένων");
        deleteDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDataBtnActionPerformed(evt);
            }
        });

        chooseCountry1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        chooseCountry1ComboBox.setName(""); // NOI18N

        chooseCountry2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chooseCountry3ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        chooseCountry3ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseCountry3ComboBoxActionPerformed(evt);
            }
        });

        astheneisCheckBox1.setForeground(new java.awt.Color(102, 255, 255));
        astheneisCheckBox1.setText("Ασθενείς που έχούν ανακάμψει");
        astheneisCheckBox1.setOpaque(false);
        astheneisCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                astheneisCheckBox1ActionPerformed(evt);
            }
        });

        krousmataCheckBox2.setForeground(new java.awt.Color(102, 255, 255));
        krousmataCheckBox2.setText("Επιβεβαιωμένα κρούσματα");
        krousmataCheckBox2.setOpaque(false);
        krousmataCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krousmataCheckBox2ActionPerformed(evt);
            }
        });

        thanatoiCheckBox3.setForeground(new java.awt.Color(102, 255, 255));
        thanatoiCheckBox3.setText("Θάνατοι");
        thanatoiCheckBox3.setOpaque(false);

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(102, 255, 255));
        label1.setText("ΕΠΙΛΕΞΤΕ ΤΟ ΕΙΔΟΣ ΔΕΔΟΜΕΝΩΝ ΠΟΥ ΣΑΣ ΕΝΔΙΑΦΕΡΟΥΝ");

        showCountryMenuBtn.setBackground(new java.awt.Color(0, 204, 204));
        showCountryMenuBtn.setText("Προβολή των δεδομένων ");
        showCountryMenuBtn.setMaximumSize(new java.awt.Dimension(137, 23));
        showCountryMenuBtn.setMinimumSize(new java.awt.Dimension(137, 23));
        showCountryMenuBtn.setName(""); // NOI18N
        showCountryMenuBtn.setPreferredSize(new java.awt.Dimension(137, 23));
        showCountryMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCountryMenuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(chooseCountry3ComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseCountry2ComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseCountry1ComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(insertCountryBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(insertDataBtn, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(98, 98, 98)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(astheneisCheckBox1)
                                    .addComponent(krousmataCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thanatoiCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteCountryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(showCountryMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseCountry1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(astheneisCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseCountry2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(krousmataCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseCountry3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thanatoiCheckBox3))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCountryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertCountryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showCountryMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu1ActionPerformed

    private void insertCountryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCountryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertCountryBtnActionPerformed

    private void insertDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertDataBtnActionPerformed

    private void deleteDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDataBtnActionPerformed
                         
         // TODO add your handling code here:
    }//GEN-LAST:event_deleteDataBtnActionPerformed

    private void deleteCountryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCountryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCountryBtnActionPerformed

    private void chooseCountry3ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseCountry3ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseCountry3ComboBoxActionPerformed

    private void showCountryMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCountryMenuBtnActionPerformed
        // TODO add your handling code here:
         new  showCountryUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_showCountryMenuBtnActionPerformed

    private void krousmataCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krousmataCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_krousmataCheckBox2ActionPerformed

    private void astheneisCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_astheneisCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_astheneisCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageDataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageDataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageDataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageDataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageDataUI().setVisible(true);
               
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox astheneisCheckBox1;
    private javax.swing.JComboBox<String> chooseCountry1ComboBox;
    private javax.swing.JComboBox<String> chooseCountry2ComboBox;
    private javax.swing.JComboBox<String> chooseCountry3ComboBox;
    private javax.swing.JButton deleteCountryBtn;
    private javax.swing.JButton deleteDataBtn;
    private javax.swing.JButton insertCountryBtn;
    private javax.swing.JButton insertDataBtn;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox krousmataCheckBox2;
    private java.awt.Label label1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JButton showCountryMenuBtn;
    private javax.swing.JCheckBox thanatoiCheckBox3;
    // End of variables declaration//GEN-END:variables
}
